# Generated by Django 5.2.4 on 2025-08-01 01:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('micine', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='asiento',
            name='estado',
            field=models.CharField(default='vendido', max_length=10),
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_compra', models.DateTimeField(auto_now_add=True)),
                ('asiento', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='micine.asiento')),
                ('funcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='micine.funcion')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SnacksCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('fecha_compra', models.DateTimeField(auto_now_add=True)),
                ('snack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='micine.snack')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
