# Generated by Django 5.2.4 on 2025-08-01 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('micine', '0002_alter_asiento_estado_compra_snackscompra'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='asiento',
            unique_together={('funcion', 'fila', 'columna')},
        ),
    ]
