# Generated by Django 5.2.4 on 2025-08-09 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('micine', '0003_alter_asiento_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compra',
            name='asiento',
        ),
        migrations.AddField(
            model_name='compra',
            name='asientos',
            field=models.ManyToManyField(to='micine.asiento'),
        ),
    ]
