# Generated by Django 5.2.4 on 2025-08-10 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('micine', '0004_remove_compra_asiento_compra_asientos'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcion',
            name='puerta_lado',
            field=models.CharField(blank=True, choices=[('izquierda', 'Izquierda'), ('derecha', 'Derecha')], max_length=10, null=True),
        ),
    ]
