# Generated by Django 5.2.4 on 2025-08-13 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('micine', '0006_votopelicula'),
    ]

    operations = [
        migrations.AddField(
            model_name='pelicula',
            name='habilitada_votacion',
            field=models.BooleanField(default=False),
        ),
    ]
