# Generated by Django 5.2.4 on 2025-08-16 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('micine', '0007_pelicula_habilitada_votacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='snack',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='snacks/'),
        ),
        migrations.AlterField(
            model_name='snackscompra',
            name='fecha_compra',
            field=models.DateField(),
        ),
    ]
